/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/foods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Foods */
        get: operations["foods_api_foods_get"];
        put?: never;
        /**
         * Create Food
         * @description Register a branded food with its label nutrition and portions.
         *
         *     Validates the barcode check digit, "davon" rows, kJ against kcal, and kcal
         *     against the macros. Use `dry_run=true` first; warnings do not block writing.
         */
        post: operations["create_food_api_foods_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/foods/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Facets
         * @description Filter values with counts for the same filters as `GET /api/foods`.
         *
         *     Each dimension is counted under the other filters, so the counts show what
         *     selecting a value would yield.
         */
        get: operations["facets_api_foods_facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/foods/barcode/{barcode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Food By Barcode
         * @description Exact lookup of a scanned or photographed EAN/UPC barcode.
         */
        get: operations["food_by_barcode_api_foods_barcode__barcode__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/foods/{slug}/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Source Text
         * @description Add a label's legal name or ingredients read from a later photo.
         *
         *     Only text fields; a label with different nutrition is a new source. BLS
         *     sources cannot be edited.
         */
        patch: operations["patch_source_text_api_foods__slug__sources__source_id__patch"];
        trace?: never;
    };
    "/api/foods/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Food Detail */
        get: operations["food_detail_api_foods__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/log/meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Meal
         * @description Log a meal: catalog foods and amounts. Nutrition is calculated, never sent.
         *
         *     A meal without items is logged with unknown nutrition. `dry_run=true`
         *     returns the meal as it would be stored, without storing it.
         */
        post: operations["create_meal_api_log_meals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/log/meals/{meal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Meal */
        get: operations["read_meal_api_log_meals__meal_id__get"];
        put?: never;
        post?: never;
        /** Delete Meal */
        delete: operations["delete_meal_api_log_meals__meal_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Meal
         * @description Change time, kind, note, or items; `items` replaces all of the meal's items.
         *
         *     Send `"kind": null` or `"note": null` to clear them. Filling in an unknown meal is an
         *     update with items.
         */
        patch: operations["update_meal_api_log_meals__meal_id__patch"];
        trace?: never;
    };
    "/api/log/days/{day}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Day
         * @description A local day's meals and totals, keeping measured, estimated, and unknown apart.
         */
        get: operations["read_day_api_log_days__day__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CatalogFacets
         * @description Filter values with counts. Each list is counted under every active
         *     filter except its own, and holds the values with at least one food plus
         *     the selected value (with count 0 if nothing matches).
         */
        CatalogFacets: {
            /** Foods */
            foods: number;
            /** Any Group */
            any_group: number;
            /** Sources */
            sources: number;
            /** Kinds */
            kinds: components["schemas"]["FacetValue"][];
            /** Source Names */
            source_names: string[];
            /** Preparation States */
            preparation_states: components["schemas"]["FacetValue"][];
            /** Groups */
            groups: components["schemas"]["FacetGroup"][];
        };
        /** Day */
        Day: {
            /** Date */
            date: string;
            /** Timezone */
            timezone: string;
            /** Meals */
            meals: components["schemas"]["Meal"][];
            counts: components["schemas"]["MealCounts"];
            totals: components["schemas"]["NutrientTotals"];
        };
        /** FacetGroup */
        FacetGroup: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Count */
            count: number;
        };
        /** FacetValue */
        FacetValue: {
            /** Value */
            value: string;
            /** Count */
            count: number;
        };
        /** FoodDetail */
        FoodDetail: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Aliases */
            aliases: string[];
            /** Kind */
            kind: string;
            /** Preparation State */
            preparation_state: string | null;
            /** Brand */
            brand: string | null;
            /** Barcode */
            barcode: string | null;
            /** Sources */
            sources: components["schemas"]["SourceDetail"][];
            /** Portions */
            portions: components["schemas"]["Portion"][];
        };
        /**
         * FoodInput
         * @description A branded food from a label photo or product database.
         */
        FoodInput: {
            /** Name */
            name: string;
            /** Brand */
            brand?: string | null;
            /** Barcode */
            barcode?: string | null;
            /**
             * Aliases
             * @default []
             */
            aliases?: string[];
            /**
             * Source Name
             * @default Product label
             */
            source_name?: string;
            /** Source Food Name */
            source_food_name?: string | null;
            /** Ingredients Text */
            ingredients_text?: string | null;
            nutrition: components["schemas"]["NutritionInput"];
            /**
             * Portions
             * @default []
             */
            portions?: components["schemas"]["PortionInput"][];
        };
        /** FoodPage */
        FoodPage: {
            /** Items */
            items: components["schemas"]["FoodSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** FoodRegistration */
        FoodRegistration: {
            /** Dry Run */
            dry_run: boolean;
            /** Slug */
            slug: string;
            /** Warnings */
            warnings: components["schemas"]["Issue"][];
            food: components["schemas"]["FoodDetail"] | null;
        };
        /** FoodSummary */
        FoodSummary: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Aliases */
            aliases: string[];
            /** Kind */
            kind: string;
            /** Preparation State */
            preparation_state: string | null;
            /** Brand */
            brand: string | null;
            /** Barcode */
            barcode: string | null;
            /** Source Count */
            source_count: number;
            source: components["schemas"]["NutritionSource"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Issue */
        Issue: {
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /**
         * ItemInput
         * @description One food in a meal: a catalog food and how much, as an amount or a portion.
         */
        ItemInput: {
            /**
             * Food
             * @description catalog slug
             */
            food: string;
            /** Source Id */
            source_id?: number | null;
            /** Amount */
            amount?: number | string | null;
            /** Portion */
            portion?: string | null;
            /** Count */
            count?: number | string | null;
            /**
             * Estimated
             * @default false
             */
            estimated?: boolean;
        };
        /** Meal */
        Meal: {
            /** Id */
            id: number;
            /** Eaten At */
            eaten_at: string;
            /** Kind */
            kind: ("breakfast" | "lunch" | "dinner" | "snack") | null;
            /** Note */
            note: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "measured" | "estimated" | "unknown";
            /** Items */
            items: components["schemas"]["MealItem"][];
            totals: components["schemas"]["NutrientTotals"];
        };
        /** MealCounts */
        MealCounts: {
            /** Measured */
            measured: number;
            /** Estimated */
            estimated: number;
            /** Unknown */
            unknown: number;
        };
        /** MealInput */
        MealInput: {
            /** Eaten At */
            eaten_at?: string | null;
            /** Kind */
            kind?: ("breakfast" | "lunch" | "dinner" | "snack") | null;
            /** Note */
            note?: string | null;
            /**
             * Items
             * @default []
             */
            items?: components["schemas"]["ItemInput"][];
        };
        /** MealItem */
        MealItem: {
            /** Id */
            id: number;
            /** Food */
            food: string;
            /** Food Name */
            food_name: string;
            /** Source Id */
            source_id: number;
            /** Source Name */
            source_name: string;
            /** Amount */
            amount: string;
            /** Unit */
            unit: string;
            /** Estimated */
            estimated: boolean;
            nutrition: components["schemas"]["Nutrition"];
        };
        /**
         * MealUpdate
         * @description Only the given fields change; `items` replaces all items.
         */
        MealUpdate: {
            /** Eaten At */
            eaten_at?: string | null;
            /** Kind */
            kind?: ("breakfast" | "lunch" | "dinner" | "snack") | null;
            /** Note */
            note?: string | null;
            /** Items */
            items?: components["schemas"]["ItemInput"][] | null;
        };
        /** NutrientTotal */
        NutrientTotal: {
            /** Measured */
            measured: string;
            /** Estimated */
            estimated: string;
            /** Items Without Value */
            items_without_value: number;
        };
        /** NutrientTotals */
        NutrientTotals: {
            energy_kj: components["schemas"]["NutrientTotal"];
            energy_kcal: components["schemas"]["NutrientTotal"];
            fat_g: components["schemas"]["NutrientTotal"];
            saturated_fat_g: components["schemas"]["NutrientTotal"];
            monounsaturated_fat_g: components["schemas"]["NutrientTotal"];
            polyunsaturated_fat_g: components["schemas"]["NutrientTotal"];
            carbs_g: components["schemas"]["NutrientTotal"];
            sugars_g: components["schemas"]["NutrientTotal"];
            polyols_g: components["schemas"]["NutrientTotal"];
            starch_g: components["schemas"]["NutrientTotal"];
            fiber_g: components["schemas"]["NutrientTotal"];
            protein_g: components["schemas"]["NutrientTotal"];
            salt_g: components["schemas"]["NutrientTotal"];
            alcohol_g: components["schemas"]["NutrientTotal"];
        };
        /** Nutrition */
        Nutrition: {
            /** Energy Kj */
            energy_kj: string | null;
            /** Energy Kcal */
            energy_kcal: string | null;
            /** Fat G */
            fat_g: string | null;
            /** Saturated Fat G */
            saturated_fat_g: string | null;
            /** Monounsaturated Fat G */
            monounsaturated_fat_g: string | null;
            /** Polyunsaturated Fat G */
            polyunsaturated_fat_g: string | null;
            /** Carbs G */
            carbs_g: string | null;
            /** Sugars G */
            sugars_g: string | null;
            /** Polyols G */
            polyols_g: string | null;
            /** Starch G */
            starch_g: string | null;
            /** Fiber G */
            fiber_g: string | null;
            /** Protein G */
            protein_g: string | null;
            /** Salt G */
            salt_g: string | null;
            /** Alcohol G */
            alcohol_g: string | null;
        };
        /**
         * NutritionInput
         * @description One nutrition column of a label, as printed (use the as-sold column).
         */
        NutritionInput: {
            /**
             * Reference Quantity
             * @default 100
             */
            reference_quantity?: number | string;
            /**
             * Reference Unit
             * @default g
             * @enum {string}
             */
            reference_unit?: "g" | "ml";
            /** Energy Kj */
            energy_kj?: number | string | null;
            /** Energy Kcal */
            energy_kcal: number | string;
            /** Fat G */
            fat_g: number | string;
            /** Saturated Fat G */
            saturated_fat_g?: number | string | null;
            /** Monounsaturated Fat G */
            monounsaturated_fat_g?: number | string | null;
            /** Polyunsaturated Fat G */
            polyunsaturated_fat_g?: number | string | null;
            /** Carbs G */
            carbs_g: number | string;
            /** Sugars G */
            sugars_g?: number | string | null;
            /** Polyols G */
            polyols_g?: number | string | null;
            /** Starch G */
            starch_g?: number | string | null;
            /** Fiber G */
            fiber_g?: number | string | null;
            /** Protein G */
            protein_g: number | string;
            /** Salt G */
            salt_g?: number | string | null;
            /** Alcohol G */
            alcohol_g?: number | string | null;
            /**
             * Upper Bounds
             * @default []
             */
            upper_bounds?: ("energy_kj" | "energy_kcal" | "fat_g" | "saturated_fat_g" | "monounsaturated_fat_g" | "polyunsaturated_fat_g" | "carbs_g" | "sugars_g" | "polyols_g" | "starch_g" | "fiber_g" | "protein_g" | "salt_g" | "alcohol_g")[];
        };
        /** NutritionSource */
        NutritionSource: {
            /** Id */
            id: number;
            /** Source Name */
            source_name: string;
            /** External Id */
            external_id: string | null;
            /** Food Name */
            food_name: string;
            /** Group Code */
            group_code: string | null;
            /** Reference Quantity */
            reference_quantity: string;
            /** Reference Unit */
            reference_unit: string;
            /** Energy Kj */
            energy_kj: string | null;
            /** Energy Kcal */
            energy_kcal: string | null;
            /** Fat G */
            fat_g: string | null;
            /** Saturated Fat G */
            saturated_fat_g: string | null;
            /** Monounsaturated Fat G */
            monounsaturated_fat_g: string | null;
            /** Polyunsaturated Fat G */
            polyunsaturated_fat_g: string | null;
            /** Carbs G */
            carbs_g: string | null;
            /** Sugars G */
            sugars_g: string | null;
            /** Polyols G */
            polyols_g: string | null;
            /** Starch G */
            starch_g: string | null;
            /** Fiber G */
            fiber_g: string | null;
            /** Protein G */
            protein_g: string | null;
            /** Salt G */
            salt_g: string | null;
            /** Alcohol G */
            alcohol_g: string | null;
            /** Protein Per 100 Kcal */
            protein_per_100_kcal: string | null;
            /** Upper Bounds */
            upper_bounds: string[];
            /** Ingredients Text */
            ingredients_text: string | null;
        };
        /** Portion */
        Portion: {
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Quantity */
            quantity: string;
            /** Unit */
            unit: string;
        };
        /** PortionInput */
        PortionInput: {
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "package" | "serving" | "piece" | "household";
            /** Quantity */
            quantity: number | string;
            /**
             * Unit
             * @enum {string}
             */
            unit: "g" | "ml";
        };
        /** SourceDetail */
        SourceDetail: {
            /** Id */
            id: number;
            /** Source Name */
            source_name: string;
            /** External Id */
            external_id: string | null;
            /** Food Name */
            food_name: string;
            /** Group Code */
            group_code: string | null;
            /** Reference Quantity */
            reference_quantity: string;
            /** Reference Unit */
            reference_unit: string;
            /** Energy Kj */
            energy_kj: string | null;
            /** Energy Kcal */
            energy_kcal: string | null;
            /** Fat G */
            fat_g: string | null;
            /** Saturated Fat G */
            saturated_fat_g: string | null;
            /** Monounsaturated Fat G */
            monounsaturated_fat_g: string | null;
            /** Polyunsaturated Fat G */
            polyunsaturated_fat_g: string | null;
            /** Carbs G */
            carbs_g: string | null;
            /** Sugars G */
            sugars_g: string | null;
            /** Polyols G */
            polyols_g: string | null;
            /** Starch G */
            starch_g: string | null;
            /** Fiber G */
            fiber_g: string | null;
            /** Protein G */
            protein_g: string | null;
            /** Salt G */
            salt_g: string | null;
            /** Alcohol G */
            alcohol_g: string | null;
            /** Protein Per 100 Kcal */
            protein_per_100_kcal: string | null;
            /** Upper Bounds */
            upper_bounds: string[];
            /** Ingredients Text */
            ingredients_text: string | null;
            /** Nutrients */
            nutrients: components["schemas"]["SourceNutrient"][];
        };
        /** SourceNutrient */
        SourceNutrient: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Amount */
            amount: string;
            /** Unit */
            unit: string;
            /** Upper Bound */
            upper_bound: boolean;
        };
        /**
         * SourceTextUpdate
         * @description Text read later from the same label, e.g. a second photo of a round cup.
         */
        SourceTextUpdate: {
            /** Food Name */
            food_name?: string | null;
            /** Ingredients Text */
            ingredients_text?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    foods_api_foods_get: {
        parameters: {
            query?: {
                q?: string | null;
                kind?: string | null;
                group?: string | null;
                source_name?: string | null;
                preparation_state?: string | null;
                min_protein?: number | string | null;
                min_protein_density?: number | string | null;
                min_fiber?: number | string | null;
                max_energy?: number | string | null;
                sort?: "relevance" | "name" | "name_desc" | "group_asc" | "group_desc" | "code_asc" | "code_desc" | "source_asc" | "source_desc" | "energy_asc" | "energy_desc" | "protein_asc" | "protein_desc" | "protein_density_asc" | "protein_density_desc" | "fat_asc" | "fat_desc" | "carbs_asc" | "carbs_desc" | "fiber_asc" | "fiber_desc";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_food_api_foods_post: {
        parameters: {
            query?: {
                dry_run?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FoodInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodRegistration"];
                };
            };
            /** @description Barcode already registered; `slug` names the food */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid or self-contradicting values; nothing written */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    facets_api_foods_facets_get: {
        parameters: {
            query?: {
                q?: string | null;
                kind?: string | null;
                group?: string | null;
                preparation_state?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogFacets"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    food_by_barcode_api_foods_barcode__barcode__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                barcode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_source_text_api_foods__slug__sources__source_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                source_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceTextUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodDetail"];
                };
            };
            /** @description No such food or source */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    food_detail_api_foods__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_meal_api_log_meals_post: {
        parameters: {
            query?: {
                dry_run?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_meal_api_log_meals__meal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_meal_api_log_meals__meal_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_meal_api_log_meals__meal_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meal_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_day_api_log_days__day__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Day"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
