/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/foods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Foods */
        get: operations["foods_api_foods_get"];
        put?: never;
        /**
         * Create Food
         * @description Register a branded food with its label nutrition and portions.
         *
         *     Validates the barcode check digit, "davon" rows, kJ against kcal, and kcal
         *     against the macros. Use `dry_run=true` first; warnings do not block writing.
         */
        post: operations["create_food_api_foods_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/foods/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Facets
         * @description Filter values with counts for the same filters as `GET /api/foods`.
         *
         *     Each dimension is counted under the other filters, so the counts show what
         *     selecting a value would yield.
         */
        get: operations["facets_api_foods_facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/foods/barcode/{barcode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Food By Barcode
         * @description Exact lookup of a scanned or photographed EAN/UPC barcode.
         */
        get: operations["food_by_barcode_api_foods_barcode__barcode__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/foods/{slug}/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Source Text
         * @description Add a label's legal name or ingredients read from a later photo.
         *
         *     Only text fields; a label with different nutrition is a new source. BLS
         *     sources cannot be edited.
         */
        patch: operations["patch_source_text_api_foods__slug__sources__source_id__patch"];
        trace?: never;
    };
    "/api/foods/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Food Detail */
        get: operations["food_detail_api_foods__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Food
         * @description Set a food's group or brand, e.g. to categorize a registered product.
         *
         *     Only the given fields change; `null` clears one.
         */
        patch: operations["patch_food_api_foods__slug__patch"];
        trace?: never;
    };
    "/api/log/meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Meal
         * @description Log a meal: catalog foods and amounts. Nutrition is calculated, never sent.
         *
         *     A meal without items is logged with unknown nutrition. `dry_run=true`
         *     returns the meal as it would be stored, without storing it.
         */
        post: operations["create_meal_api_log_meals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/log/meals/{meal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Meal */
        get: operations["read_meal_api_log_meals__meal_id__get"];
        put?: never;
        post?: never;
        /** Delete Meal */
        delete: operations["delete_meal_api_log_meals__meal_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Meal
         * @description Change time, kind, note, or items; `items` replaces all of the meal's items.
         *
         *     Send `"kind": null` or `"note": null` to clear them. Filling in an unknown meal is an
         *     update with items.
         */
        patch: operations["update_meal_api_log_meals__meal_id__patch"];
        trace?: never;
    };
    "/api/log/days/{day}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Day
         * @description A local day's meals and totals, keeping measured, estimated, and unknown apart.
         */
        get: operations["read_day_api_log_days__day__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Recipes
         * @description Recipes, most recently cooked or created first; `q` matches name words.
         */
        get: operations["read_recipes_api_recipes_get"];
        put?: never;
        /**
         * Post Recipe
         * @description Create a recipe with version 1, from ingredients, a cook, or another recipe's version.
         *
         *     `forked_from` develops it from another recipe's version; `from_cook` saves
         *     what went into a cook. `dry_run=true` returns it without storing.
         */
        post: operations["post_recipe_api_recipes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Recipe
         * @description A recipe with every version (newest first), forks, and its cooks.
         */
        get: operations["read_recipe_api_recipes__slug__get"];
        put?: never;
        post?: never;
        /**
         * Remove Recipe
         * @description Delete a recipe that was never cooked or forked.
         */
        delete: operations["remove_recipe_api_recipes__slug__delete"];
        options?: never;
        head?: never;
        /**
         * Patch Recipe
         * @description Rename a recipe or change its note.
         */
        patch: operations["patch_recipe_api_recipes__slug__patch"];
        trace?: never;
    };
    "/api/recipes/{slug}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Version
         * @description Add a version: changed ingredients or portions, with a note on what and why.
         *
         *     Missing fields come from `from_cook` (ingredients, portions) and the parent
         *     version (ingredients, portions, steps). The parent defaults to the cook's
         *     version, else the latest.
         */
        post: operations["post_version_api_recipes__slug__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{slug}/versions/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Version
         * @description Change a version's note or steps; ingredients and portions are fixed.
         */
        patch: operations["patch_version_api_recipes__slug__versions__number__patch"];
        trace?: never;
    };
    "/api/cooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Cooks
         * @description The cooking log, newest first: by recipe slug, name words, or local days.
         */
        get: operations["read_cooks_api_cooks_get"];
        put?: never;
        /**
         * Post Cook
         * @description Log a cook: a recipe version and what actually went in, split into portions.
         *
         *     Without `items`, the version's ingredients are used. Without a recipe, the
         *     cook is improvised and needs `name`, `portions`, and `items`.
         */
        post: operations["post_cook_api_cooks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cooks/{cook_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Cook
         * @description A cook with its ingredients, nutrition per portion, and changes to its version.
         */
        get: operations["read_cook_api_cooks__cook_id__get"];
        put?: never;
        post?: never;
        /**
         * Remove Cook
         * @description Delete a cook nothing was logged from.
         */
        delete: operations["remove_cook_api_cooks__cook_id__delete"];
        options?: never;
        head?: never;
        /**
         * Patch Cook
         * @description Correct a cook; meals eaten from it follow. `items` replaces all ingredients.
         */
        patch: operations["patch_cook_api_cooks__cook_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Amount
         * @description An amount of a catalog source with its nutrition.
         */
        Amount: {
            /** Id */
            id: number;
            /** Food */
            food: string;
            /** Food Name */
            food_name: string;
            /** Variant Of */
            variant_of: string | null;
            /** Variants */
            variants: number;
            /** Source Id */
            source_id: number;
            /** Source Name */
            source_name: string;
            /** Amount */
            amount: string;
            /** Unit */
            unit: string;
            /** Estimated */
            estimated: boolean;
            nutrition: components["schemas"]["Nutrition"];
        };
        /**
         * CatalogFacets
         * @description Filter values with counts. Each list is counted under every active
         *     filter except its own, and holds the values with at least one food plus
         *     the selected value (with count 0 if nothing matches).
         */
        CatalogFacets: {
            /** Foods */
            foods: number;
            /** Any Group */
            any_group: number;
            /** Sources */
            sources: number;
            /** Kinds */
            kinds: components["schemas"]["FacetValue"][];
            /** Source Names */
            source_names: string[];
            /** Preparation States */
            preparation_states: components["schemas"]["FacetValue"][];
            /** Groups */
            groups: components["schemas"]["FacetGroup"][];
            /** Brands */
            brands: components["schemas"]["FacetValue"][];
            /** Incomplete */
            incomplete: number;
        };
        /**
         * Change
         * @description One ingredient that differs, before and after; empty means absent.
         *
         *     A branded product and its generic food are the same ingredient, so a swap
         *     is one change with different foods on either side.
         */
        Change: {
            /** Planned */
            planned: components["schemas"]["ChangePart"][];
            /** Actual */
            actual: components["schemas"]["ChangePart"][];
        };
        /** ChangePart */
        ChangePart: {
            /** Food */
            food: string;
            /** Food Name */
            food_name: string;
            /** Amount */
            amount: string;
            /** Unit */
            unit: string;
        };
        /** Cook */
        Cook: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            recipe: components["schemas"]["RecipeRef"] | null;
            /** Version */
            version: number | null;
            /** Cooked At */
            cooked_at: string;
            /** Portions */
            portions: string;
            /** Weight G */
            weight_g: string | null;
            /** Note */
            note: string | null;
            /** Portions Eaten */
            portions_eaten: string;
            /** Portions Left */
            portions_left: string;
            /**
             * Status
             * @enum {string}
             */
            status: "measured" | "estimated" | "unknown";
            totals: components["schemas"]["NutrientTotals"];
            per_portion: components["schemas"]["NutrientTotals"];
            /** Items */
            items: components["schemas"]["Amount"][];
            /** Changes */
            changes: components["schemas"]["Change"][];
        };
        /**
         * CookInput
         * @description A cook from a recipe version, or an improvised one with a name and items.
         */
        CookInput: {
            /** Recipe */
            recipe?: string | null;
            /** Version */
            version?: number | null;
            /** Name */
            name?: string | null;
            /** Cooked At */
            cooked_at?: string | null;
            /** Portions */
            portions?: number | string | null;
            /** Weight G */
            weight_g?: number | string | null;
            /** Note */
            note?: string | null;
            /** Items */
            items?: components["schemas"]["FoodAmount"][] | null;
        };
        /** CookSummary */
        CookSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            recipe: components["schemas"]["RecipeRef"] | null;
            /** Version */
            version: number | null;
            /** Cooked At */
            cooked_at: string;
            /** Portions */
            portions: string;
            /** Weight G */
            weight_g: string | null;
            /** Note */
            note: string | null;
            /** Portions Eaten */
            portions_eaten: string;
            /** Portions Left */
            portions_left: string;
            /**
             * Status
             * @enum {string}
             */
            status: "measured" | "estimated" | "unknown";
            totals: components["schemas"]["NutrientTotals"];
            per_portion: components["schemas"]["NutrientTotals"];
        };
        /**
         * CookUpdate
         * @description Only the given fields change; `items` replaces all ingredients.
         */
        CookUpdate: {
            /** Name */
            name?: string | null;
            /** Cooked At */
            cooked_at?: string | null;
            /** Portions */
            portions?: number | string | null;
            /** Weight G */
            weight_g?: number | string | null;
            /** Note */
            note?: string | null;
            /** Items */
            items?: components["schemas"]["FoodAmount"][] | null;
        };
        /** Day */
        Day: {
            /** Date */
            date: string;
            /** Timezone */
            timezone: string;
            /** Meals */
            meals: components["schemas"]["Meal"][];
            counts: components["schemas"]["MealCounts"];
            totals: components["schemas"]["NutrientTotals"];
        };
        /** FacetGroup */
        FacetGroup: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Count */
            count: number;
        };
        /** FacetValue */
        FacetValue: {
            /** Value */
            value: string;
            /** Count */
            count: number;
        };
        /**
         * FoodAmount
         * @description A catalog food and how much, as an amount or a portion.
         */
        FoodAmount: {
            /**
             * Food
             * @description catalog slug
             */
            food: string;
            /** Source Id */
            source_id?: number | null;
            /** Amount */
            amount?: number | string | null;
            /** Portion */
            portion?: string | null;
            /** Count */
            count?: number | string | null;
            /**
             * Estimated
             * @default false
             */
            estimated?: boolean;
        };
        /** FoodDetail */
        FoodDetail: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Aliases */
            aliases: string[];
            /** Kind */
            kind: string;
            /** Preparation State */
            preparation_state: string | null;
            /** Food Group */
            food_group: string | null;
            /** Food Group Name */
            food_group_name: string | null;
            /** Brand */
            brand: string | null;
            /** Barcode */
            barcode: string | null;
            /** Label Gaps */
            label_gaps: components["schemas"]["LabelGap"][];
            /** Sources */
            sources: components["schemas"]["SourceDetail"][];
            /** Portions */
            portions: components["schemas"]["Portion"][];
            variant_of: components["schemas"]["FoodRef"] | null;
            /** Variants */
            variants: components["schemas"]["Variant"][];
        };
        /**
         * FoodInput
         * @description A branded food from a label photo or product database.
         */
        FoodInput: {
            /** Name */
            name: string;
            /** Brand */
            brand?: string | null;
            /** Barcode */
            barcode?: string | null;
            /** Food Group */
            food_group?: string | null;
            /**
             * Aliases
             * @default []
             */
            aliases?: string[];
            /**
             * Source Name
             * @default Product label
             */
            source_name?: string;
            /** Source Food Name */
            source_food_name?: string | null;
            /** Ingredients Text */
            ingredients_text?: string | null;
            nutrition: components["schemas"]["NutritionInput"];
            /**
             * Portions
             * @default []
             */
            portions?: components["schemas"]["PortionInput"][];
            /** Variant Of */
            variant_of?: string | null;
        };
        /** FoodPage */
        FoodPage: {
            /** Items */
            items: components["schemas"]["FoodSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** FoodRef */
        FoodRef: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
        };
        /** FoodRegistration */
        FoodRegistration: {
            /** Dry Run */
            dry_run: boolean;
            /** Slug */
            slug: string;
            /** Warnings */
            warnings: components["schemas"]["Issue"][];
            food: components["schemas"]["FoodDetail"] | null;
        };
        /** FoodSummary */
        FoodSummary: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Aliases */
            aliases: string[];
            /** Kind */
            kind: string;
            /** Preparation State */
            preparation_state: string | null;
            /** Food Group */
            food_group: string | null;
            /** Food Group Name */
            food_group_name: string | null;
            /** Brand */
            brand: string | null;
            /** Barcode */
            barcode: string | null;
            /** Source Count */
            source_count: number;
            source: components["schemas"]["NutritionSource"] | null;
            /** Label Gaps */
            label_gaps: components["schemas"]["LabelGap"][];
        };
        /**
         * FoodUpdate
         * @description Catalog fields of a food; only the given ones change, null clears.
         */
        FoodUpdate: {
            /** Food Group */
            food_group?: string | null;
            /** Brand */
            brand?: string | null;
            /** Variant Of */
            variant_of?: string | null;
        };
        /** Fork */
        Fork: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** From Version */
            from_version: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Issue */
        Issue: {
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /**
         * ItemInput
         * @description One thing eaten: a catalog food (amount or portion), or portions of a cook.
         */
        ItemInput: {
            /**
             * Food
             * @description catalog slug
             */
            food?: string | null;
            /** Cook */
            cook?: number | null;
            /** Source Id */
            source_id?: number | null;
            /** Amount */
            amount?: number | string | null;
            /** Portion */
            portion?: string | null;
            /** Count */
            count?: number | string | null;
            /**
             * Estimated
             * @default false
             */
            estimated?: boolean;
        };
        /**
         * LabelGap
         * @description Something a product's current label still lacks, to photograph next time.
         */
        LabelGap: {
            /** Field */
            field: string;
            /** Label */
            label: string;
        };
        /** Meal */
        Meal: {
            /** Id */
            id: number;
            /** Eaten At */
            eaten_at: string;
            /** Kind */
            kind: ("breakfast" | "lunch" | "dinner" | "snack") | null;
            /** Note */
            note: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "measured" | "estimated" | "unknown";
            /** Items */
            items: components["schemas"]["MealItem"][];
            totals: components["schemas"]["NutrientTotals"];
        };
        /** MealCounts */
        MealCounts: {
            /** Measured */
            measured: number;
            /** Estimated */
            estimated: number;
            /** Unknown */
            unknown: number;
        };
        /** MealInput */
        MealInput: {
            /** Eaten At */
            eaten_at?: string | null;
            /** Kind */
            kind?: ("breakfast" | "lunch" | "dinner" | "snack") | null;
            /** Note */
            note?: string | null;
            /**
             * Items
             * @default []
             */
            items?: components["schemas"]["ItemInput"][];
        };
        /**
         * MealItem
         * @description A catalog food, or portions of a cook (then `food` and `source_id` are null).
         */
        MealItem: {
            /** Id */
            id: number;
            /** Food */
            food: string | null;
            /** Food Name */
            food_name: string;
            /** Source Id */
            source_id: number | null;
            /** Source Name */
            source_name: string | null;
            /** Cook Id */
            cook_id: number | null;
            recipe: components["schemas"]["RecipeRef"] | null;
            /** Cooked At */
            cooked_at: string | null;
            /** Amount */
            amount: string;
            /** Unit */
            unit: string;
            /** Estimated */
            estimated: boolean;
            nutrition: components["schemas"]["Nutrition"];
        };
        /**
         * MealUpdate
         * @description Only the given fields change; `items` replaces all items.
         */
        MealUpdate: {
            /** Eaten At */
            eaten_at?: string | null;
            /** Kind */
            kind?: ("breakfast" | "lunch" | "dinner" | "snack") | null;
            /** Note */
            note?: string | null;
            /** Items */
            items?: components["schemas"]["ItemInput"][] | null;
        };
        /** NutrientTotal */
        NutrientTotal: {
            /** Measured */
            measured: string;
            /** Estimated */
            estimated: string;
            /** Items Without Value */
            items_without_value: number;
        };
        /** NutrientTotals */
        NutrientTotals: {
            energy_kj: components["schemas"]["NutrientTotal"];
            energy_kcal: components["schemas"]["NutrientTotal"];
            fat_g: components["schemas"]["NutrientTotal"];
            saturated_fat_g: components["schemas"]["NutrientTotal"];
            monounsaturated_fat_g: components["schemas"]["NutrientTotal"];
            polyunsaturated_fat_g: components["schemas"]["NutrientTotal"];
            carbs_g: components["schemas"]["NutrientTotal"];
            sugars_g: components["schemas"]["NutrientTotal"];
            polyols_g: components["schemas"]["NutrientTotal"];
            starch_g: components["schemas"]["NutrientTotal"];
            fiber_g: components["schemas"]["NutrientTotal"];
            protein_g: components["schemas"]["NutrientTotal"];
            salt_g: components["schemas"]["NutrientTotal"];
            alcohol_g: components["schemas"]["NutrientTotal"];
        };
        /** Nutrition */
        Nutrition: {
            /** Energy Kj */
            energy_kj: string | null;
            /** Energy Kcal */
            energy_kcal: string | null;
            /** Fat G */
            fat_g: string | null;
            /** Saturated Fat G */
            saturated_fat_g: string | null;
            /** Monounsaturated Fat G */
            monounsaturated_fat_g: string | null;
            /** Polyunsaturated Fat G */
            polyunsaturated_fat_g: string | null;
            /** Carbs G */
            carbs_g: string | null;
            /** Sugars G */
            sugars_g: string | null;
            /** Polyols G */
            polyols_g: string | null;
            /** Starch G */
            starch_g: string | null;
            /** Fiber G */
            fiber_g: string | null;
            /** Protein G */
            protein_g: string | null;
            /** Salt G */
            salt_g: string | null;
            /** Alcohol G */
            alcohol_g: string | null;
        };
        /**
         * NutritionInput
         * @description One nutrition column of a label, as printed (use the as-sold column).
         */
        NutritionInput: {
            /**
             * Reference Quantity
             * @default 100
             */
            reference_quantity?: number | string;
            /**
             * Reference Unit
             * @default g
             * @enum {string}
             */
            reference_unit?: "g" | "ml";
            /** Energy Kj */
            energy_kj?: number | string | null;
            /** Energy Kcal */
            energy_kcal: number | string;
            /** Fat G */
            fat_g: number | string;
            /** Saturated Fat G */
            saturated_fat_g?: number | string | null;
            /** Monounsaturated Fat G */
            monounsaturated_fat_g?: number | string | null;
            /** Polyunsaturated Fat G */
            polyunsaturated_fat_g?: number | string | null;
            /** Carbs G */
            carbs_g: number | string;
            /** Sugars G */
            sugars_g?: number | string | null;
            /** Polyols G */
            polyols_g?: number | string | null;
            /** Starch G */
            starch_g?: number | string | null;
            /** Fiber G */
            fiber_g?: number | string | null;
            /** Protein G */
            protein_g: number | string;
            /** Salt G */
            salt_g?: number | string | null;
            /** Alcohol G */
            alcohol_g?: number | string | null;
            /**
             * Upper Bounds
             * @default []
             */
            upper_bounds?: ("energy_kj" | "energy_kcal" | "fat_g" | "saturated_fat_g" | "monounsaturated_fat_g" | "polyunsaturated_fat_g" | "carbs_g" | "sugars_g" | "polyols_g" | "starch_g" | "fiber_g" | "protein_g" | "salt_g" | "alcohol_g")[];
        };
        /** NutritionSource */
        NutritionSource: {
            /** Id */
            id: number;
            /** Source Name */
            source_name: string;
            /** External Id */
            external_id: string | null;
            /** Food Name */
            food_name: string;
            /** Reference Quantity */
            reference_quantity: string;
            /** Reference Unit */
            reference_unit: string;
            /** Energy Kj */
            energy_kj: string | null;
            /** Energy Kcal */
            energy_kcal: string | null;
            /** Fat G */
            fat_g: string | null;
            /** Saturated Fat G */
            saturated_fat_g: string | null;
            /** Monounsaturated Fat G */
            monounsaturated_fat_g: string | null;
            /** Polyunsaturated Fat G */
            polyunsaturated_fat_g: string | null;
            /** Carbs G */
            carbs_g: string | null;
            /** Sugars G */
            sugars_g: string | null;
            /** Polyols G */
            polyols_g: string | null;
            /** Starch G */
            starch_g: string | null;
            /** Fiber G */
            fiber_g: string | null;
            /** Protein G */
            protein_g: string | null;
            /** Salt G */
            salt_g: string | null;
            /** Alcohol G */
            alcohol_g: string | null;
            /** Protein Per 100 Kcal */
            protein_per_100_kcal: string | null;
            /** Upper Bounds */
            upper_bounds: string[];
            /** Ingredients Text */
            ingredients_text: string | null;
        };
        /** ParentRef */
        ParentRef: {
            /** Recipe */
            recipe: string;
            /** Recipe Name */
            recipe_name: string;
            /** Number */
            number: number;
        };
        /** Portion */
        Portion: {
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Quantity */
            quantity: string;
            /** Unit */
            unit: string;
        };
        /** PortionInput */
        PortionInput: {
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "package" | "serving" | "piece" | "household";
            /** Quantity */
            quantity: number | string;
            /**
             * Unit
             * @enum {string}
             */
            unit: "g" | "ml";
        };
        /** Recipe */
        Recipe: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Note */
            note: string | null;
            /** Created At */
            created_at: string;
            /** Versions */
            versions: components["schemas"]["Version"][];
            /** Forks */
            forks: components["schemas"]["Fork"][];
            /** Cooks */
            cooks: components["schemas"]["CookSummary"][];
        };
        /**
         * RecipeInput
         * @description A new recipe and its first version.
         *
         *     Ingredients and portions come from `items` and `portions`, otherwise from
         *     `from_cook`, otherwise from the `forked_from` version.
         */
        RecipeInput: {
            /** Name */
            name: string;
            /** Note */
            note?: string | null;
            /** Items */
            items?: components["schemas"]["FoodAmount"][] | null;
            /** Portions */
            portions?: number | string | null;
            /** Instructions */
            instructions?: string | null;
            forked_from?: components["schemas"]["VersionRef"] | null;
            /** From Cook */
            from_cook?: number | null;
        };
        /** RecipeRef */
        RecipeRef: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
        };
        /** RecipeSummary */
        RecipeSummary: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Note */
            note: string | null;
            /** Latest Version */
            latest_version: number;
            /** Cooks */
            cooks: number;
            /** Last Cooked At */
            last_cooked_at: string | null;
            /** Portions */
            portions: string;
            per_portion: components["schemas"]["NutrientTotals"];
        };
        /** RecipeUpdate */
        RecipeUpdate: {
            /** Name */
            name?: string | null;
            /** Note */
            note?: string | null;
        };
        /** SourceDetail */
        SourceDetail: {
            /** Id */
            id: number;
            /** Source Name */
            source_name: string;
            /** External Id */
            external_id: string | null;
            /** Food Name */
            food_name: string;
            /** Reference Quantity */
            reference_quantity: string;
            /** Reference Unit */
            reference_unit: string;
            /** Energy Kj */
            energy_kj: string | null;
            /** Energy Kcal */
            energy_kcal: string | null;
            /** Fat G */
            fat_g: string | null;
            /** Saturated Fat G */
            saturated_fat_g: string | null;
            /** Monounsaturated Fat G */
            monounsaturated_fat_g: string | null;
            /** Polyunsaturated Fat G */
            polyunsaturated_fat_g: string | null;
            /** Carbs G */
            carbs_g: string | null;
            /** Sugars G */
            sugars_g: string | null;
            /** Polyols G */
            polyols_g: string | null;
            /** Starch G */
            starch_g: string | null;
            /** Fiber G */
            fiber_g: string | null;
            /** Protein G */
            protein_g: string | null;
            /** Salt G */
            salt_g: string | null;
            /** Alcohol G */
            alcohol_g: string | null;
            /** Protein Per 100 Kcal */
            protein_per_100_kcal: string | null;
            /** Upper Bounds */
            upper_bounds: string[];
            /** Ingredients Text */
            ingredients_text: string | null;
            /** Nutrients */
            nutrients: components["schemas"]["SourceNutrient"][];
        };
        /** SourceNutrient */
        SourceNutrient: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Amount */
            amount: string;
            /** Unit */
            unit: string;
            /** Upper Bound */
            upper_bound: boolean;
        };
        /**
         * SourceTextUpdate
         * @description Text read later from the same label, e.g. a second photo of a round cup.
         */
        SourceTextUpdate: {
            /** Food Name */
            food_name?: string | null;
            /** Ingredients Text */
            ingredients_text?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Variant
         * @description A branded product that is a kind of this generic food, with its current values.
         */
        Variant: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Brand */
            brand: string | null;
            /** Reference Quantity */
            reference_quantity: string | null;
            /** Reference Unit */
            reference_unit: string | null;
            /** Energy Kcal */
            energy_kcal: string | null;
            /** Protein G */
            protein_g: string | null;
        };
        /** Version */
        Version: {
            /** Id */
            id: number;
            /** Number */
            number: number;
            parent: components["schemas"]["ParentRef"] | null;
            /** Changes */
            changes: components["schemas"]["Change"][];
            /** From Cook Id */
            from_cook_id: number | null;
            /** Note */
            note: string | null;
            /** Instructions */
            instructions: string | null;
            /** Portions */
            portions: string;
            /** Created At */
            created_at: string;
            /** Cooks */
            cooks: number;
            /**
             * Status
             * @enum {string}
             */
            status: "measured" | "estimated" | "unknown";
            /** Items */
            items: components["schemas"]["Amount"][];
            totals: components["schemas"]["NutrientTotals"];
            per_portion: components["schemas"]["NutrientTotals"];
        };
        /**
         * VersionInput
         * @description A new version; anything not given comes from `from_cook` or the parent.
         */
        VersionInput: {
            /** Note */
            note?: string | null;
            /** Items */
            items?: components["schemas"]["FoodAmount"][] | null;
            /** Portions */
            portions?: number | string | null;
            /** Instructions */
            instructions?: string | null;
            /** Parent */
            parent?: number | null;
            /** From Cook */
            from_cook?: number | null;
        };
        /** VersionRef */
        VersionRef: {
            /** Recipe */
            recipe: string;
            /** Version */
            version?: number | null;
        };
        /**
         * VersionUpdate
         * @description Only text changes; different ingredients or portions are a new version.
         */
        VersionUpdate: {
            /** Note */
            note?: string | null;
            /** Instructions */
            instructions?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    foods_api_foods_get: {
        parameters: {
            query?: {
                q?: string | null;
                kind?: string | null;
                group?: string | null;
                brand?: string | null;
                source_name?: string | null;
                preparation_state?: string | null;
                min_protein?: number | string | null;
                min_protein_density?: number | string | null;
                min_fiber?: number | string | null;
                max_energy?: number | string | null;
                /** @description only products whose label still lacks something */
                incomplete?: boolean;
                sort?: "relevance" | "name" | "name_desc" | "group_asc" | "group_desc" | "code_asc" | "code_desc" | "source_asc" | "source_desc" | "energy_asc" | "energy_desc" | "protein_asc" | "protein_desc" | "protein_density_asc" | "protein_density_desc" | "fat_asc" | "fat_desc" | "carbs_asc" | "carbs_desc" | "fiber_asc" | "fiber_desc";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_food_api_foods_post: {
        parameters: {
            query?: {
                dry_run?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FoodInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodRegistration"];
                };
            };
            /** @description Barcode already registered; `slug` names the food */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid or self-contradicting values; nothing written */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    facets_api_foods_facets_get: {
        parameters: {
            query?: {
                q?: string | null;
                kind?: string | null;
                group?: string | null;
                brand?: string | null;
                preparation_state?: string | null;
                incomplete?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogFacets"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    food_by_barcode_api_foods_barcode__barcode__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                barcode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_source_text_api_foods__slug__sources__source_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                source_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceTextUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodDetail"];
                };
            };
            /** @description No such food or source */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    food_detail_api_foods__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_food_api_foods__slug__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FoodUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodDetail"];
                };
            };
            /** @description No such food */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_meal_api_log_meals_post: {
        parameters: {
            query?: {
                dry_run?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_meal_api_log_meals__meal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_meal_api_log_meals__meal_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_meal_api_log_meals__meal_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meal_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_day_api_log_days__day__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Day"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_recipes_api_recipes_get: {
        parameters: {
            query?: {
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_recipe_api_recipes_post: {
        parameters: {
            query?: {
                dry_run?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recipe"];
                };
            };
            /** @description Invalid input; nothing written */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    read_recipe_api_recipes__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recipe"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_recipe_api_recipes__slug__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_recipe_api_recipes__slug__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recipe"];
                };
            };
            /** @description Invalid input; nothing written */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_version_api_recipes__slug__versions_post: {
        parameters: {
            query?: {
                dry_run?: boolean;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
            /** @description Invalid input; nothing written */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patch_version_api_recipes__slug__versions__number__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_cooks_api_cooks_get: {
        parameters: {
            query?: {
                recipe?: string | null;
                q?: string | null;
                since?: string | null;
                until?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CookSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_cook_api_cooks_post: {
        parameters: {
            query?: {
                dry_run?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CookInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cook"];
                };
            };
            /** @description Invalid input; nothing written */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    read_cook_api_cooks__cook_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cook_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cook"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_cook_api_cooks__cook_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cook_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_cook_api_cooks__cook_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cook_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CookUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cook"];
                };
            };
            /** @description Invalid input; nothing written */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
