/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FoodsIndexRouteImport } from './routes/foods/index'
import { Route as FoodsSlugRouteImport } from './routes/foods/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsIndexRoute = FoodsIndexRouteImport.update({
  id: '/foods/',
  path: '/foods/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsSlugRoute = FoodsSlugRouteImport.update({
  id: '/foods/$slug',
  path: '/foods/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/foods/$slug': typeof FoodsSlugRoute
  '/foods/': typeof FoodsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/foods/$slug': typeof FoodsSlugRoute
  '/foods': typeof FoodsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/foods/$slug': typeof FoodsSlugRoute
  '/foods/': typeof FoodsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/foods/$slug' | '/foods/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/foods/$slug' | '/foods'
  id: '__root__' | '/' | '/foods/$slug' | '/foods/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FoodsSlugRoute: typeof FoodsSlugRoute
  FoodsIndexRoute: typeof FoodsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods/': {
      id: '/foods/'
      path: '/foods'
      fullPath: '/foods/'
      preLoaderRoute: typeof FoodsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods/$slug': {
      id: '/foods/$slug'
      path: '/foods/$slug'
      fullPath: '/foods/$slug'
      preLoaderRoute: typeof FoodsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FoodsSlugRoute: FoodsSlugRoute,
  FoodsIndexRoute: FoodsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
