//  @ts-check

import { tanstackConfig } from "@tanstack/eslint-config"

export default [
  ...tanstackConfig,
  {
    rules: {
      "import/no-cycle": "off",
      "import/order": "off",
      "sort-imports": "off",
      "@typescript-eslint/array-type": "off",
      "@typescript-eslint/require-await": "off",
      "pnpm/json-enforce-catalog": "off",
    },
  },
  {
    // shadcn components are vendored and regenerated by its CLI; the others
    // are generated by the router plugin and `make web-types`.
    ignores: [
      "eslint.config.js",
      ".prettierrc",
      "dist/**",
      ".output/**",
      "src/components/ui/**",
      "src/routeTree.gen.ts",
      "src/lib/api/schema.gen.ts",
    ],
  },
]
